### ISSUE TITLE
run bug

### ISSUE THREAD

**Issue by BulletTrain** [brewfactory/BrewMobile#50]
Hello,I clone this,and run carthage bootstrap --platform iOS.

**\* Building scheme "ISO8601DateFormatter" in ISO8601ForCocoa.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

```
Available destinations for the "ISO8601DateFormatter" scheme:
    { platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
    { platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
    { platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
    { platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
    { platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
    { platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
    { platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }
```

A shell task failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

```
Available destinations for the "ISO8601DateFormatter" scheme:
    { platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
    { platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
    { platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
    { platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
    { platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
    { platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
    { platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }
```

Can you help me ?

**Comment by vasarhelyia** [comment]
Hi, I'm happy to help! Can you try a `carthage bootstrap --platform iOS --no-use-binaries` instead? 

Let me know if it still not working, I will check it out then.

**Comment by BulletTrain** [comment]
$ carthage bootstrap --platform iOS --no-u
se-binaries
*** Checking out SIOSocket at "e3d4f2cd09eab6a1ce0980b3c9fbec2a81a6c4bd"
*** Checking out SwiftyJSON at "2.3.0"
*** Checking out Result at "76f9a972ed61ff872b731460bc610c8acbfae58c"
*** Checking out iso-8601-date-formatter at "103ee049f0ce2fd66b16b814adbc6b741959ce64"
*** Checking out ReactiveCocoa at "v4.0-alpha.1"
*** xcodebuild output can be found in /var/folders/y1/yb0mtvps4bj1ly533qs8j4sw0000gn/T/carthage-xcodebuild.pk384C.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "SocketIOFramework" in SocketIO.xcodeproj
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "ISO8601DateFormatter" in ISO8601ForCocoa.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

	Available destinations for the "ISO8601DateFormatter" scheme:
		{ platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }
A shell task failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

	Available destinations for the "ISO8601DateFormatter" scheme:
		{ platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }

It still not working.

**Comment by vasarhelyia** [comment]
I pushed an update of the ISO8601 framework, please try again. Try `carthage update --platform iOS --no-use-binaries` this time. Let me know how it worked.

**Comment by BulletTrain** [comment]
$  carthage update --platform iOS --no-use-binaries
*** Cloning SwiftyJSON
*** Cloning ReactiveCocoa
*** Cloning iso-8601-date-formatter
*** Cloning SIOSocket
*** Cloning Result
*** Checking out Result at "76f9a972ed61ff872b731460bc610c8acbfae58c"
*** Checking out SIOSocket at "e3d4f2cd09eab6a1ce0980b3c9fbec2a81a6c4bd"
*** Checking out SwiftyJSON at "2.3.0"
*** Checking out iso-8601-date-formatter at "11cd171ff5b659c8a1c55864810a3e3f5075853b"
*** Checking out ReactiveCocoa at "v4.0-alpha.1"
*** xcodebuild output can be found in /var/folders/y1/yb0mtvps4bj1ly533qs8j4sw0000gn/T/carthage-xcodebuild.wPzNwO.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "SocketIOFramework" in SocketIO.xcodeproj
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "ISO8601DateFormatter" in ISO8601ForCocoa.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

	Available destinations for the "ISO8601DateFormatter" scheme:
		{ platform:OS X, arch:x86_64 }
		{ platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }
A shell task failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:DEEFBEEB-76E8-4219-A473-4AD279D601E8 }

	Available destinations for the "ISO8601DateFormatter" scheme:
		{ platform:OS X, arch:x86_64 }
		{ platform:iOS Simulator, id:A8BDCF3A-13F9-4C6E-A873-F181DFB7744C, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:2AC64A3E-9D3C-42EA-86C8-2CF4F3833E1C, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:08E581EF-02B5-4693-91C4-C156FEDFA220, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:599C1EDC-3F12-44EB-8658-FCC973B2B3F5, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:6FFBFE37-DA99-4948-9320-BFE51FD291E6, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B522C410-1E4F-4F0A-BF40-EEAC451A01A0, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:7F94FA91-1028-4BD5-91AC-42A5F007EEDC, OS:9.0, name:iPhone 6s Plus }

it still not work.

**Comment by vasarhelyia** [comment]
Do you have a developer certificate? Which version of Xcode do you have installed? Which version of command line tools do you have installed? Have you tried cleaning? If you can please go through these steps and make sure you have the latest & greatest from everything I will be happy to accept a PR if you have a solution for a specific problem. With the current setup and Xcode 7 everything's green on the CI, with clean installs.

**Comment by BulletTrain** [comment]
I use xcode 7.0.1 and OS is osx10.11.I don't know why.I have tried these steps. But still not work.

**Comment by vasarhelyia** [comment]
I found your problem, it is related to 10.11 I guess. Setting the `ISO8601` framework target architecture to standard solved it. I committed it into the Checkouts folder of Carthage, so cleaning/pulling and shooting a `carthage build --platform iOS --no-use-binaries` should let you build it now. If not, please set the above mentioned step manually until I ask some help from the owner of the `ISO8601` framework. Now it's working for me with Xcode 7.1 under OSX 10.11.

**Comment by BulletTrain** [comment]
Wait you ask some help from the owner of the ISO8601 framework.hahaha, this framework can't work.

**Comment by vasarhelyia** [comment]
What do you mean? I just told you how can you make it work. Do you understand the concept of open source? If you find a problem you let the owner know at least, but fixing it in a pull request would be the normal. Please, learn to contribute and watch your attitude these people put a lot of effort to make things work for everyone. And you are welcome for solving your problem.

**Comment by BulletTrain** [comment]
Just have a joke.I am sorry.I have run it.Thank you.
